insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(101,'HCL',956.1);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(102,'Infosys',101.5);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(103,'INeuron',852.8);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(104,'Navis',541.1);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(105,'TechMahindra',625.3);